"""remocao nome unico em pacientes

Revision ID: 72f253aa9827
Revises: 39879302f8aa
Create Date: 2024-09-22 17:21:16.425059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f253aa9827'
down_revision: Union[str, None] = '39879302f8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pacientes_nome_key', 'pacientes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pacientes_nome_key', 'pacientes', ['nome'])
    # ### end Alembic commands ###
